---
# tasks file for php

- name: Install PHP on Ubuntu
  include: Debian.yml
  when:
    - ansible_os_family == "Debian"

- name: Install PHP on CentOS
  include: Redhat.yml
  when:
    - ansible_os_family == "RedHat"

