---
# tasks file for php

- name: Ubuntu
  include: Debian.yml
  when: 
    - ansible_os_family == "Debian"
#    - ansible_distribution_major_version == "14"

#- name: Ubuntu
#  include: Debian16.yml
#  when: 
#    - ansible_os_family == "Debian"
#    - ansible_distribution_major_version == "16"

- name: CentOS
  include: Redhat6.yml
  when: #ansible_os_family == "RedHat" and ansible_distribution_version == 6
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "6"

- name: CentOS
  include: Redhat7.yml
  when: #ansible_distribution == "RedHat" and ansible_distribution_version == 7
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

